In [1]:
import warnings

import pandas as pd
import numpy as np

from jre_utils.datapath import factor_data_paths
from jre_utils.constants import BLACKLISTED_AREAS

warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)

In [2]:
all_area_population_estimate_path = factor_data_paths["processed"]["population"]["submunicipality"]
all_area_taxpayer_count_path = factor_data_paths["processed"]["taxpayer"]["submunicipality"]

taxable_income_processed_path = factor_data_paths["processed"]["taxable_income"]["municipality"]
taxable_income_unprocessed_path = factor_data_paths["unprocessed"]["taxable_income"]["municipality"]

In [3]:
population_df = pd.read_csv(all_area_population_estimate_path)
taxpayer_df = pd.read_csv(all_area_taxpayer_count_path)

taxable_income_df = pd.read_csv(taxable_income_unprocessed_path)
taxable_income_df = taxable_income_df[~taxable_income_df["area"].isin(BLACKLISTED_AREAS)]
taxable_income_df = taxable_income_df.merge(taxpayer_df, on=["year", "area_code"], suffixes=["", "_x"], how="left")

taxable_income_df = taxable_income_df[taxable_income_df["taxable_income"].apply(lambda x: x.isdigit())]
taxable_income_df["taxable_income"] = taxable_income_df["taxable_income"].astype(float)

taxable_income_df["taxable_income_per_taxpayer"] = taxable_income_df["taxable_income"] / taxable_income_df["taxpayer_count"]

taxable_income_df = taxable_income_df.sort_values(by=["year", "area_code"]) # for growth calculation
taxable_income_df = taxable_income_df[~taxable_income_df[["year", "area_code"]].duplicated()]

taxable_income_df["taxable_income_growth"] = taxable_income_df.groupby("area_code")["taxable_income"].pct_change()
taxable_income_df["taxable_income_per_taxpayer_growth"] = taxable_income_df.groupby("area_code")["taxable_income_per_taxpayer"].pct_change()
taxable_income_df = taxable_income_df.sort_values(by=["year", "area_code"], ascending=[False, True])

taxable_income_df = taxable_income_df.drop(columns=["area_x"])

taxable_income_df

,year,area_code,area,taxable_income,taxpayer_count,taxpayer_count_growth,taxpayer_count_log,taxpayer_count_log_normalized_yearly,taxpayer_count_growth_normalized_yearly,taxable_income_per_taxpayer,taxable_income_growth,taxable_income_per_taxpayer_growth
0,2021,1100,Hokkaido Sapporo-shi,2.971366e+09,906411.0,0.003444,5.957326,2.853349,0.336425,3278.166013,0.032400,0.028857
11,2021,1202,Hokkaido Hakodate-shi,3.194402e+08,107534.0,-0.015292,5.031550,1.505360,-0.705828,2970.597039,0.016612,0.032400
12,2021,1203,Hokkaido Otaru-shi,1.243333e+08,46190.0,-0.013582,4.664557,0.970996,-0.610690,2691.778827,0.028630,0.042793
13,2021,1204,Hokkaido Asahikawa-shi,4.193510e+08,142560.0,0.000681,5.154001,1.683656,0.182719,2941.575168,0.038224,0.037518
14,2021,1205,Hokkaido Muroran-shi,1.052086e+08,34835.0,-0.010875,4.542028,0.792585,-0.460104,3020.199455,0.009337,0.020434
...,...,...,...,...,...,...,...,...,...,...,...,...
70810,1985,47361,Okinawa-ken Kumejima-cho,3.992455e+06,1819.0,NaN,3.260071,-1.095376,NaN,2194.862562,NaN,NaN
70811,1985,47362,Okinawa-ken Yaese-cho,9.023653e+06,4997.0,NaN,3.698796,-0.386018,NaN,1805.814088,NaN,NaN
70812,1985,47375,Okinawa-ken Tarama-son,4.395900e+05,196.0,NaN,2.294466,-2.656629,NaN,2242.806122,NaN,NaN
70813,1985,47381,Okinawa-ken Taketomi-cho,1.525627e+06,663.0,NaN,2.822168,-1.803406,NaN,2301.096531,NaN,NaN
70814,1985,47382,Okinawa-ken Yonaguni-cho,8.240200e+05,446.0,NaN,2.650308,-2.081282,NaN,1847.578475,NaN,NaN

In [9]:
log_normalize_columns = [
    "taxable_income",
    "taxable_income_per_taxpayer",
]

normalize_columns = [
    "taxable_income_growth",
    "taxable_income_per_taxpayer_growth",
]

for column in log_normalize_columns:
    taxable_income_df[f"{column}_log"] = taxable_income_df[column].apply(
        lambda x: np.log10(1 + x)
    )
    taxable_income_df[f"{column}_log_normalized_yearly"] = taxable_income_df.groupby(
        "year"
    )[f"{column}_log"].transform(lambda x: (x - x.mean()) / x.std())

for column in normalize_columns:
    taxable_income_df[f"{column}_normalized_yearly"] = taxable_income_df.groupby(
        "year"
    )[column].transform(lambda x: (x - x.mean()) / x.std())

taxable_income_df.to_csv(taxable_income_processed_path, index=False)

In [4]:
taxable_income_df[taxable_income_df["area_code"] == 13102]

,year,area_code,area,taxable_income,taxpayer_count,taxpayer_count_growth,taxpayer_count_log,taxpayer_count_log_normalized_yearly,taxpayer_count_growth_normalized_yearly,taxable_income_per_taxpayer,taxable_income_growth,taxable_income_per_taxpayer_growth
658,2021,13102,Tokyo-to Chuo-ku,725351426.0,101810.0,0.017520,5.007795,1.470771,1.119426,7124.559729,0.059288,0.041049
2573,2020,13102,Tokyo-to Chuo-ku,684753903.0,100057.0,0.030082,5.000252,1.460485,1.701562,6843.638156,0.021457,-0.008373
4488,2019,13102,Tokyo-to Chuo-ku,670370026.0,97135.0,0.039266,4.987380,1.445581,2.001342,6901.426118,0.108315,0.066440
6403,2018,13102,Tokyo-to Chuo-ku,604855042.0,93465.0,0.054755,4.970654,1.429122,2.455725,6471.460354,0.075667,0.019827
8318,2017,13102,Tokyo-to Chuo-ku,562306834.0,88613.0,0.053637,4.947502,1.402201,1.953868,6345.647185,0.082041,0.026958
10233,2016,13102,Tokyo-to Chuo-ku,519672356.0,84102.0,0.041653,4.924811,1.377242,1.463130,6179.072507,0.081736,0.038480
12148,2015,13102,Tokyo-to Chuo-ku,480405927.0,80739.0,0.052097,4.907089,1.360499,2.721036,5950.109947,0.055433,0.003171
14063,2014,13102,Tokyo-to Chuo-ku,455174215.0,76741.0,0.034259,4.885033,1.330405,1.570505,5931.304192,0.103712,0.067153
15978,2013,13102,Tokyo-to Chuo-ku,412402889.0,74199.0,0.034089,4.870404,1.309807,0.724862,5558.065324,0.051194,0.016541
17893,2012,13102,Tokyo-to Chuo-ku,392318713.0,71753.0,0.032373,4.855846,1.294434,0.730156,5467.628016,0.039087,0.006504
19808,2011,13102,Tokyo-to Chuo-ku,377561047.0,69503.0,0.019240,4.842010,1.276150,1.089684,5432.298563,0.022785,0.003478
21723,2010,13102,Tokyo-to Chuo-ku,369149895.0,68191.0,0.016653,4.833733,1.263104,2.014019,5413.469446,-0.097716,-0.112496
23638,2009,13102,Tokyo-to Chuo-ku,409128333.0,67074.0,0.053314,4.826561,1.232883,2.912055,6099.656096,0.056263,0.002800
25553,2008,13102,Tokyo-to Chuo-ku,387335589.0,63679.0,0.047318,4.804003,1.198487,2.196780,6082.626753,0.038176,-0.008728
27468,2007,13102,Tokyo-to Chuo-ku,373092395.0,60802.0,0.060654,4.783925,1.173139,2.788365,6136.186227,0.129960,0.065343
29383,2006,13102,Tokyo-to Chuo-ku,330181866.0,57325.0,0.116315,4.758352,1.141124,1.538554,5759.823218,0.124003,0.006887
31298,2005,13102,Tokyo-to Chuo-ku,293755435.0,51352.0,0.097429,4.710566,1.115486,2.725024,5720.428318,0.162538,0.059329
33213,2004,13102,Tokyo-to Chuo-ku,252684535.0,46793.0,0.042904,4.670190,1.073904,2.128444,5400.049901,0.066303,0.022437
35128,2003,13102,Tokyo-to Chuo-ku,236972442.0,44868.0,0.050330,4.651946,1.048460,3.245645,5281.546804,0.037598,-0.012122
37043,2002,13102,Tokyo-to Chuo-ku,228385612.0,42718.0,0.045165,4.630621,0.999806,2.669210,5346.355447,0.030796,-0.013749
38958,2001,13102,Tokyo-to Chuo-ku,221562416.0,40872.0,0.056861,4.611437,0.961723,3.117664,5420.885105,0.114074,0.054134
40873,2000,13102,Tokyo-to Chuo-ku,198875941.0,38673.0,0.036671,4.587419,0.919278,2.183044,5142.500996,0.065035,0.027361
42788,1999,13102,Tokyo-to Chuo-ku,186731775.0,37305.0,0.019290,4.571779,0.885206,1.024309,5005.542823,-0.003756,-0.022610
44703,1998,13102,Tokyo-to Chuo-ku,187435764.0,36599.0,0.004805,4.563481,0.869258,0.391927,5121.335665,-0.008421,-0.013162
46618,1997,13102,Tokyo-to Chuo-ku,189027583.0,36424.0,-0.006221,4.561400,0.865544,-0.806532,5189.643724,-0.007685,-0.001473
48532,1996,13102,Tokyo-to Chuo-ku,190491500.0,36652.0,-0.005994,4.564110,0.879735,-0.654403,5197.301648,-0.023099,-0.017208
50446,1995,13102,Tokyo-to Chuo-ku,194995619.0,36873.0,-0.019465,4.566720,0.892360,-0.974733,5288.303610,-0.043532,-0.024545
52360,1994,13102,Tokyo-to Chuo-ku,203870596.0,37605.0,-0.096403,4.575257,0.910545,-3.323065,5421.369392,-0.003405,0.102920
54272,1993,13102,Tokyo-to Chuo-ku,204567172.0,41617.0,0.067294,4.619281,0.987357,1.389106,4915.471370,-0.234318,-0.282595
56184,1992,13102,Tokyo-to Chuo-ku,267169715.0,38993.0,0.008875,4.590998,0.962354,-0.850898,6851.735311,0.021737,0.012749
58096,1991,13102,Tokyo-to Chuo-ku,261485775.0,38650.0,-0.005967,4.587161,0.980710,-1.752361,6765.479301,0.085605,0.092122
60008,1990,13102,Tokyo-to Chuo-ku,240866321.0,38882.0,0.019562,4.589760,1.017220,1.162436,6194.802762,0.207003,0.183845
61920,1989,13102,Tokyo-to Chuo-ku,199557363.0,38136.0,-0.056693,4.581347,0.995614,-2.265400,5232.781702,0.051822,0.115037
63830,1988,13102,Tokyo-to Chuo-ku,189725418.0,40428.0,-0.017737,4.606693,1.046190,-0.324296,4692.921193,0.149244,0.169995
65740,1987,13102,Tokyo-to Chuo-ku,165087219.0,41158.0,-0.011314,4.614465,1.064775,-1.145334,4011.060280,0.097197,0.109753
67650,1986,13102,Tokyo-to Chuo-ku,150462756.0,41629.0,-0.005756,4.619406,1.088405,-0.634089,3614.373538,0.057031,0.063151
69560,1985,13102,Tokyo-to Chuo-ku,142344675.0,41870.0,NaN,4.621913,1.106537,NaN,3399.681753,NaN,NaN