In [1]:
import warnings

import pandas as pd

from jre_utils.datapath import DATA_DIRECTORY_PATH

warnings.filterwarnings("ignore")
pd.set_option("display.max_columns", None)

In [35]:
taxable_income_with_area_code_path = (
    f"{DATA_DIRECTORY_PATH}/exploratory/taxable_income_with_area_code.csv"
)
taxable_income_with_area_code_df = pd.read_csv(taxable_income_with_area_code_path)
taxable_income_with_area_code_df = taxable_income_with_area_code_df[taxable_income_with_area_code_df["year"] == 2021]
taxable_income_with_area_code_df

      year  area_code                               area taxable_income
0     2021       1100               Hokkaido Sapporo-shi     2971365734
1     2021       1101       Hokkaido Sapporo-shi Chuo-ku              -
2     2021       1102       Hokkaido Sapporo-shi Kita-ku              -
3     2021       1103    Hokkaido Sapporo-shi Higashi-ku              -
4     2021       1104  Hokkaido Sapporo-shi Shiroishi-ku              -
...    ...        ...                                ...            ...
1911  2021      47361           Okinawa-ken Kumejima-cho        7099523
1912  2021      47362              Okinawa-ken Yaese-cho       33063062
1913  2021      47375             Okinawa-ken Tarama-son         839123
1914  2021      47381           Okinawa-ken Taketomi-cho        3948297
1915  2021      47382           Okinawa-ken Yonaguni-cho        2536602

[1916 rows x 4 columns]

In [29]:
area_code_to_area = pd.Series(
    taxable_income_with_area_code_df["area"],
    index=taxable_income_with_area_code_df["area_code"],
).to_dict()

In [38]:
local_finance_survey_cover = f"{DATA_DIRECTORY_PATH}/exploratory/local_finance_survey_cover.csv"
local_finance_survey_cover_df = pd.read_csv(local_finance_survey_cover)
local_finance_survey_cover_df = local_finance_survey_cover_df[local_finance_survey_cover_df["year"] == 2021]
local_finance_survey_cover_df = local_finance_survey_cover_df[
    local_finance_survey_cover_df["area_code"].apply(lambda x: x.isdigit())
]
local_finance_survey_cover_df["area_code"] = local_finance_survey_cover_df["area_code"].astype(int)
local_finance_survey_cover_df["area_code_shortened"] = local_finance_survey_cover_df["area_code"] // 10
local_finance_survey_cover_df

,year,area_code,Prefecture,Municipality,standard_fiscal_revenue,baseline_fiscal_requirements,standard_tax_revenue,standard_fiscal_scale,financial_bonds_issuable,fiscal_power_index,area_code_shortened
0,2021,11002,北海道,札幌市,293985964,420205828,365755970,556234732,63821827,72,1100
1,2021,12025,北海道,函館市,28205539,60568134,35595708,72224159,4265856,48,1202
2,2021,12033,北海道,小樽市,12715747,27690380,16008401,32467609,1534578,46,1203
3,2021,12041,北海道,旭川市,36325413,69708432,45623671,84408471,5401781,53,1204
4,2021,12050,北海道,室蘭市,11728909,18899499,14853349,23437612,1413265,63,1205
...,...,...,...,...,...,...,...,...,...,...,...
3095,2021,478407,沖縄県,中部北環境施設組合,0,0,0,0,0,0,47840
3096,2021,478423,沖縄県,那覇市・南風原町環境施設組合,0,0,0,0,0,0,47842
3097,2021,478431,沖縄県,那覇港管理組合,0,0,0,0,0,0,47843
3098,2021,478440,沖縄県,沖縄県介護保険広域連合,0,0,0,0,0,0,47844
3099,2021,478458,沖縄県,沖縄県後期高齢者医療広域連合,0,0,0,0,0,0,47845

In [45]:
taxable_income_with_area_code_df.merge(local_finance_survey_cover_df, left_on="area_code", right_on="area_code_shortened")

,year_x,area_code_x,area,taxable_income,year_y,area_code_y,Prefecture,Municipality,standard_fiscal_revenue,baseline_fiscal_requirements,standard_tax_revenue,standard_fiscal_scale,financial_bonds_issuable,fiscal_power_index,area_code_shortened
0,2021,1100,Hokkaido Sapporo-shi,2971365734,2021,11002,北海道,札幌市,293985964,420205828,365755970,556234732,63821827,72,1100
1,2021,1202,Hokkaido Hakodate-shi,319440182,2021,12025,北海道,函館市,28205539,60568134,35595708,72224159,4265856,48,1202
2,2021,1203,Hokkaido Otaru-shi,124333264,2021,12033,北海道,小樽市,12715747,27690380,16008401,32467609,1534578,46,1203
3,2021,1204,Hokkaido Asahikawa-shi,419350956,2021,12041,北海道,旭川市,36325413,69708432,45623671,84408471,5401781,53,1204
4,2021,1205,Hokkaido Muroran-shi,105208648,2021,12050,北海道,室蘭市,11728909,18899499,14853349,23437612,1413265,63,1205
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1736,2021,47361,Okinawa-ken Kumejima-cho,7099523,2021,473618,沖縄県,久米島町,726652,3918877,903955,4232345,136165,20,47361
1737,2021,47362,Okinawa-ken Yaese-cho,33063062,2021,473626,沖縄県,八重瀬町,2815812,6693503,3521280,7743068,358033,43,47362
1738,2021,47375,Okinawa-ken Tarama-son,839123,2021,473758,沖縄県,多良間村,123488,1190084,147524,1251086,36966,11,47375
1739,2021,47381,Okinawa-ken Taketomi-cho,3948297,2021,473812,沖縄県,竹富町,480048,3724257,604210,3984521,124532,15,47381
1740,2021,47382,Okinawa-ken Yonaguni-cho,2536602,2021,473821,沖縄県,与那国町,244882,1692547,303628,1806634,55341,15,47382

In [ ]:
# Merge all the local financial situation survey data into one dataset

# Merge all columns for an year
# Merge all years